### ISSUE TITLE
Invalid redeclaration of synthesized implementation for protocol requirement 'allCases'

### ISSUE THREAD

**Issue by gbesler** [Peter-Schorn/SpotifyAPI#13]
Hello @Peter-Schorn , thanks for this great library. 
However, I cannot build it in my project. I have tried from version 1.1.2 to 1.5.1 and I get same error:

Invalid redeclaration of synthesized implementation for protocol requirement 'allCases'

XCode returns several errors and I am attaching them:

<img width="819" alt="Screen Shot 2021-04-16 at 10 07 33" src="https://user-images.githubusercontent.com/6095238/114985630-b0e74c80-9e9b-11eb-8949-b79715283124.png">

<img width="789" alt="Screen Shot 2021-04-16 at 10 09 46" src="https://user-images.githubusercontent.com/6095238/114985790-e429db80-9e9b-11eb-86af-4e15aa012b50.png">

I have no idea how to fix those errors. Could you please guide?

**Comment by Peter-Schorn** [comment]
The library builds just fine for me. Try building it by itself without attaching it to any project. If it builds fine by itself, then link me to the full project that you are using it in.

**Comment by Peter-Schorn** [comment]
Ok, I think I know exactly why you are unable to build the library: You're using a version of swift prior to 5.2, which was when   [SE-0249](https://github.com/apple/swift-evolution/blob/main/proposals/0249-key-path-literal-function-expressions.md) was introduced, which allows you to use key path literals as functions. Is there a reason why you haven't updated yet?

**Comment by jminutaglio** [comment]
Same issue:
<img width="337" alt="Screen Shot 2021-04-26 at 4 11 13 PM" src="https://user-images.githubusercontent.com/49879291/116144214-0eed0e80-a6aa-11eb-98d6-321f872456dd.png">

This was introduced w/ Xcode Version 12.5 (12E262); same code complied w/out issue in the previous Xcode version.

(Swift is 5.2)

Any ideas?

**Comment by Peter-Schorn** [comment]
Xcode 12.5 was released along with swift 5.4, which I'm about to update to.

**Comment by Peter-Schorn** [comment]
You can depend on the `swift-tools-5-1` branch if you want, which supports Swift 5.1 and 5.2, unlike master. However, I will make no guarantees about keeping it up to date with master. Is there a reason why you're still using Swift 5.2?

**Comment by jminutaglio** [comment]
apologies, typo: Swift 5.x.  

LMK if you have the same experience w/ Xcode 12.5

**Comment by Peter-Schorn** [comment]
> apologies, typo: Swift 5.x.

So then which minor version are you using? It's important. master does not compile on versions of swift before 5.2, because this was when Key Path Expressions as Functions was introduced

**Comment by jminutaglio** [comment]
The Xcode 12.4/Swift version (on which the library complied w/out issue):
<img width="669" alt="Screen Shot 2021-04-26 at 4 50 10 PM" src="https://user-images.githubusercontent.com/49879291/116149012-a4d76800-a6af-11eb-9d87-ed6a6ad2ecee.png">
 
The Xcode 12.5 version (on which the library has the compiler errors above):
<img width="747" alt="Screen Shot 2021-04-26 at 4 50 13 PM" src="https://user-images.githubusercontent.com/49879291/116149090-b7ea3800-a6af-11eb-8714-2b9d324cacc3.png">

I haven't tried the swift-tools-5-1 branch.

**Comment by Peter-Schorn** [comment]
So it's not compiling on swift 5.4? I'll have to look into that. I'm still waiting for the Xcode update to complete.

**Comment by jminutaglio** [comment]
Correct.  Upon update to 5.4/Xcode 12.5 the errors showed during a build.  There was no change to the code, just an Xcode update.

**Comment by Peter-Schorn** [comment]
Ok I figured it out: It's a bug. See [here](https://forums.swift.org/t/invalid-redeclaration-of-synthesized-implementation-for-protocol-requirement-allcases/47715).

**Comment by Peter-Schorn** [comment]
I've just pushed a commit that fixes this issue.

**Comment by jminutaglio** [comment]
TY for addressing so quickly.  You are appreciated! 

:)
