### ISSUE TITLE
Ambigious use case of 'allCases'

### ISSUE THREAD

**Issue by ridmaur** [Peter-Schorn/SpotifyAPI#19]
After installing latest version of Xcode (Version 12.5 (12E262)) when rebuilding my project I am getting ambiguous use of 'allCases' on Scope.allCases. I think it is caused by redefining the Scopes array as a Set

**Comment by Peter-Schorn** [comment]
This is due to a bug in swift 5.4 which I just fixed in 1.6.1. See #13.
