### ISSUE TITLE
How to append  [SpotifyWebAPI.Playlist<PlaylistItemsReference>]

### ISSUE THREAD

**Issue by kimfucious** [Peter-Schorn/SpotifyAPI#32]
HI @Peter-Schorn,

I've been putting your wonderful library to great use, thanks for making this!

Question:

I'm fetching a user's playlists and successfully storing them in "state" as a published variable:
```swift
@Published var currentUsersSpotifyPlaylists = [SpotifyWebAPI.Playlist<PlaylistItemsReference>]()
```
I can populate this initially with:
```swift
@MainActor
func getSpotifyUsersPlaylists() async {
    do {
        Logger.log(.info, "Fetching user's Spotify playlists")
        if spotify.isAuthorized {
            Logger.log(.success, "Spotify is Authorized")
            Logger.log(.fetch, "Fetching user's Spotify playlists...")
            let playlistsPage = try await spotify.api.currentUserPlaylists(limit: 50)
                .extendPages(spotify.api)
                .awaitSingleValue()
            networkManager.currentUsersSpotifyPlaylists = playlistsPage?.items ?? []
        } else {
            Logger.log(.warning, "Spotify is not Authorized")
            networkManager.viewToShow = .tracklistTabView
        }
    } catch {
        print(error)
    }
}
```
In some cases the user will create a playlist using this:
```swift
func createSpotifyPlaylist(playlistDetails: PlaylistDetails, spotifyUserProfile: SpotifyUser) async throws -> PlaylistItems? {
        var playlistToReturn: SpotifyWebAPI.Playlist<PlaylistItems>?
        do {
            Logger.log(.info, "Creating Spotify playlist: \(String(describing: playlistDetails.name))...")
            let result = try await spotify.api.createPlaylist(for: spotifyUserProfile.uri, playlistDetails)
                .awaitSingleValue()
            if result != nil {
                Logger.log(.success, "Playlist created!")
                print(result as Any)
                playlistToReturn = result!
            }
        } catch {
            print("Error Saving Tracks to Playlist", error)
            throw error
        }
        guard playlistToReturn != nil else {
            Logger.log(.warning, "No playlist to return!")
            return nil
        }
        await self.addImageToSpotifyPlaylist(playlistId: playlistToReturn!.uri)
        return playlistToReturn!.items
    }
```
If the above returns the items, I'd like update "state" by appending `currentSpotifyUsersPlaylists` with said items; however,  after quite a while of futzing around, I cannot figure out how to do that, as `.append()` and `+ operator` are obviously the wrong tools for the job here when dealing with the type at hand.

Any tips?

```swift
DispatchQueue.main.async {
  self.currentSpotifyUsersPlaylists = ??? // <= what goes here?
}
```
Thanks!

**Comment by Peter-Schorn** [comment]
> 
```swift
print("Error Saving Tracks to Playlist", error)
```
The above code is not saving any tracks to a playlist.

> If the above returns the items, I'd like update "state" by appending currentSpotifyUsersPlaylists with said items

The playlist that you create using [SpotifyAPI.createPlaylist(for:_:)][1] will not contain any items (tracks/episodes). The documentation mentions this. Why would you expect a just-created playlist to contain items?

The return type of the aforementioned method is `AnyPublisher<Playlist<PlaylistItems>, Error>`, meaning that the type of `playlistToReturn` is `Playlist<PlaylistItems>`. But the type of `currentUsersSpotifyPlaylists` is `[Playlist<PlaylistItemsReference>]`. You can only append values of type `Playlist<PlaylistItemsReference>`—not `Playlist<PlaylistItems>`— to this array. Swift is a statically typed language. You should know this.

After you create a new playlist and, optionally, add items to it (which the posted code doesn't do yet), **you should make another call to `getSpotifyUsersPlaylists`, which will then update `currentUsersSpotifyPlaylists` with the newly-created playlist**. Spotify's database may not update immediately after you create the playlist, so you can call this function repeatedly  —with an exponentially increasing delay—until `currentUsersSpotifyPlaylists` contains a playlist with the URI of the newly-created playlist.

>
```swift
let playlistsPage = try await spotify.api.currentUserPlaylists(limit: 50)
    .extendPages(spotify.api)
    .awaitSingleValue()
```

This doesn't do what you think it does. [Publisher.extendPages(_:maxExtraPages:)][2] returns a publisher that publishes *multiple* values: one for each page of results. `Publisher.awaitSingleValue` only waits for a *single* value from the publisher. Therefore, you're only retrieving a single page of playlists. 

What you need is a way of asynchronously collecting *all* values produced by the publisher into an array:
```swift
let playlists: [Playlist<PlaylistItemsReference>] = try await spotify.api
    .currentUserPlaylists(limit: 50)
    .extendPages(spotify.api)
    .values
    .reduce(into: [], { result, page in
        result.append(contentsOf: page.items)
    })

networkManager.currentUsersSpotifyPlaylists = playlists
```

[Publisher.values][3] has the same behavior as `Publisher.awaitValues` in #28, but I trust Apple's implementation more than my own. The `reduce` method collects the `items` array from each `PagingObject` into a single array.


[1]: https://peter-schorn.github.io/SpotifyAPI/Classes/SpotifyAPI.html#/s:13SpotifyWebAPI0aC0CA2A0A25ScopeAuthorizationManagerRzrlE14createPlaylist3for_7Combine12AnyPublisherVyAA0H0VyAA12PagingObjectVyAA0H13ItemContainerVyAA0hO0OGGGs5Error_pGAA0A14URIConvertible_p_AA0H7DetailsVtF
[2]: https://peter-schorn.github.io/SpotifyAPI/Extensions/Publisher.html#/s:7Combine9PublisherP13SpotifyWebAPIAD9Paginated6OutputRpzrlE11extendPages_08maxExtraI0AA03AnyB0VyAGs5Error_pGAD0cE0Cyqd__G_SiSgtAD0C20AuthorizationManagerRd__lF
[3]: https://developer.apple.com/documentation/combine/publisher/values-v7nz

**Comment by Peter-Schorn** [comment]
>
```swift
if result != nil {
    // ...
    playlistToReturn = result!
}
```
Stop using this pattern. Don't use a boolean test for whether an optional is `nil` and then force-unwrap it and assign it to a non-optional variable. Instead use the if-let pattern:
```swift
if let result = result {
    // ...
    playlistToReturn = result
}
```

**Comment by Peter-Schorn** [comment]
> Regarding `awaitSingleValue()`, I've implemented that heavily, so I guess, I'll begin replacing that with `values`/`reduce` pattern where it makes sense to do so, though `awaitSingleValue()` has been working as expected thus far.

If only one page of results exists, then the behavior will be the same. But you should never assume only one page of results exists.
