### ISSUE TITLE
FUNDING.yml request

### ISSUE THREAD

**Issue by ptrkstr** [Peter-Schorn/SpotifyAPI#33]
This repo is incredible 👏👏👏
Would you be willing to add a FUNDING.yml, preferably using github sponsors? 
I'd love to sponsor this work.

**Comment by Peter-Schorn** [comment]
Sure. How do you suggest that I accept money?

**Comment by ptrkstr** [comment]
https://github.com/sponsors

Once you sign up it'll add a sponsor button to the repo.

**Comment by will-lumley** [comment]
100% agree, this repo is criminally underappreciated. 
Would love to donate money through Github sponsors.

**Comment by ptrkstr** [comment]
> 100% agree, this repo is criminally underappreciated. 
> 
> Would love to donate money through Github sponsors.

@will-lumley its heartwarming to see another person agree :)

**Comment by Peter-Schorn** [comment]
![IMG_small](https://user-images.githubusercontent.com/58197311/179500600-5e046981-4c6c-4fb8-a661-aa7c8283202a.JPG)

**Comment by Peter-Schorn** [comment]
The review for my sponsorship is in progress.

**Comment by Peter-Schorn** [comment]
Added support for Github Sponsors in 49af602f0e7485da650aab680ff19cd93f191ddf.
