### ISSUE TITLE
`extendPages` aren't available on `.search`

### ISSUE THREAD

**Issue by shaundon** [Peter-Schorn/SpotifyAPI#35]
I've noticed that the `extendPages` and `extendPagesConcurrently` methods aren't available when using the `.search` function.

The below code produces the following error:

```
Referencing instance method 'extendPages(_:maxExtraPages:)' on 'Publisher' requires that 'SearchResult' conform to 'Paginated'
```

```swift
let api = SpotifyAPI(
  authorizationManager: AuthorizationCodeFlowManager(
  clientId: clientId, 
  clientSecret: clientSecret
))

var cancellables = Set<AnyCancellable>()

api.search(query: "My query", categories: [.tracks], limit: 50)
  .extendPages(api)
  .receive(on: RunLoop.main)
  .sink(
    receiveCompletion: { completion in
      // Handle completion
    },
    receiveValue: { resultsPage in
      // Handle results page
    }
  )
  .store(in: &cancellables)
```

I get the same error when trying `extendPagesConcurrently`, too.

As far as I can tell from [Spotify's API documentation](https://developer.spotify.com/documentation/web-api/reference/#/operations/search), paging should work fine on this endpoint, as it does for others.

Is this a deliberate omission, or is it a bug?

**Comment by shaundon** [comment]
Update: I took a look at the source code for `SearchResult` and it appears that the properties within implement `PagingObject` (e.g. `PagingObject<Track>`). So I might just be trying to extend the pages in the wrong way.

**Comment by Peter-Schorn** [comment]
`SearchResult` does not conform to `Paginated` because it does not have a `next` property. This is the only requirement for conforming to this protocol. As you alluded to, you must use the properties within `SearchResult` for pagination.

**Comment by shaundon** [comment]
Thanks for the detailed response!
