### ISSUE TITLE
Creating a private playlist doesn't work; it is always public

### ISSUE THREAD

**Issue by bbauman1** [Peter-Schorn/SpotifyAPI#39]
Thanks for your work making this package. It's super useful.

I'm creating a playlist with this endpoint:

```
createPlaylist(
    for userURI: SpotifyURIConvertible,
    _ playlistDetails: PlaylistDetails
)
```

and setting `isPublic` to `false` in `PlaylistDetails`. The scopes I have authorized are:

```
[
    .playlistModifyPrivate,
    .playlistModifyPublic,
]
```

The playlist creation succeeds, but it is a public playlist. Any help would be appreciated if you've ran into this before or are able to repro.

**Comment by Peter-Schorn** [comment]
Provide a minimum reproducible example.

**Comment by Peter-Schorn** [comment]
Looks like this is an issue on Spotify's end. Post about it [here](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
