### ISSUE TITLE
Remove SpotifyExampleContent from SpotifyAPI in Swift Package

### ISSUE THREAD

**Issue by gregggreg** [Peter-Schorn/SpotifyAPI#45]
If you include SpotifyAPI using Swift Package Manager, it includes the SpotifyExampleContent in your resulting app, adding several megabytes of unused content into your app. I've removed it from my fork and would love to see it merged so that I don't have to rely on my fork. Thanks, this project is super useful.

**Comment by will-lumley** [comment]
+1, I just checked also and it's adding 4.8MB to my app 😱
@Peter-Schorn Are there any plans to spin off the `SpotifyExampleContent` into its own library that can then be pulled into `SpotifyAPI` when necessary? Happy to help out / work on it.

**Comment by Peter-Schorn** [comment]
I would accept a PR that moves `SpotifyExampleContent` into a separate library.

**Comment by Peter-Schorn** [comment]
Implemented in latest commit. Will be availble in next release.

**Comment by Peter-Schorn** [comment]
Implemented in version `3.0.0`.
