### ISSUE TITLE
Build errors on macOS Ventura

### ISSUE THREAD

**Issue by nkleemann** [Peter-Schorn/SpotifyAPI#53]
Hi, I'm trying to use your package on macOS Ventura, Xcode 15.1 and I'm getting build/linker errors (undefined symbols). I'm not quite sure which target in the package causes them, could we debug this together?

EDIT: reformulated post after a first, uninformed, inquiry

**Comment by Peter-Schorn** [comment]
Are you still experiencing these build/linker errors? Can't reproduce.
