### ISSUE TITLE
Spotify redirection works but doesn't login

### ISSUE THREAD

**Issue by Xen0o2** [Peter-Schorn/SpotifyAPI#54]
Hi, I have cloned the SpotifyAPIExample but edit some features, and now I have a problem, when I first login, everything worked, but after logout using this `Button(action: spotify.api.authorizationManager.deauthorize)` it doesn't work anymore.

When I click login, I'm redirected to Safari, I can login to Spotify, I can redirect to the app but nothing happen, it just keep saying that I'm not logged in.

Thanks for your help

**Comment by Peter-Schorn** [comment]
Did you resolve this issue? If not, please make the source code of your app available in order for me to investigate.
