### ISSUE TITLE
New Album Type

### ISSUE THREAD

**Issue by kylebusy** [Peter-Schorn/SpotifyAPI#56]
Is it possible to get "ep" added as an Album Type? When browsing new releases, if the resulting New Albums contains an EP then the DecodeSpotifyObject bombs with the below error.

 - debugDescription: "Cannot initialize AlbumType from invalid String value ep"

**Comment by Peter-Schorn** [comment]
Verify this works: 52a0e30f9f36221ee73da30004e4e6e5a389ab2f

**Comment by kylebusy** [comment]
Just what I needed, thank you so much for the quick turnaround!

**Comment by tkess7** [comment]
@Peter-Schorn Just curious do you typically create a new release for fixes like this? I ran into this same issue and I'm on the latest version. I'm getting around it now by using the commit you provided.

**Comment by Peter-Schorn** [comment]
I will release a new version within the next couple of days.

**Comment by tkess7** [comment]
Thank you. Also thank you for this API, it's amazing!
