### ISSUE TITLE
"extendPagesConcurrently" causes crash

### ISSUE THREAD

**Issue by wiencheck** [Peter-Schorn/SpotifyAPI#60]
This crash is affecting a lot of my users however I've not been able to reproduce it on my side.
The crash cause is `Swift runtime failure: Stride size must not be zero`

<img width="1920" alt="Screenshot 2024-05-20 at 09 49 43" src="https://github.com/Peter-Schorn/SpotifyAPI/assets/25985996/34069261-ea40-4e8e-95fb-973c09368a08">

**Comment by Peter-Schorn** [comment]
I have identified the root cause of this bug and will deploy a fix soon. It's caused by Spotify returning a value of `0` in the JSON payload for the `PagingObject.limit` property, which specifies the _maximum_ number of items in the _current_ page (and the step for the page offset interval). You cannot iterate over an interval with a step of 0.

**Comment by Peter-Schorn** [comment]
Please Try 4297eb6f4161fc0f813bf76ce9d4cf8d5cc13f7c.

**Comment by wiencheck** [comment]
It seems that those changes broke the extendPages functionality because now it only downloads first page and returns. I rolled back to 3.0.0 and then was able to download all pages from PagingObject so 3.0.1 definitely broke some logic

**Comment by Peter-Schorn** [comment]
Oh noo. Will take a look.

**Comment by Peter-Schorn** [comment]
I think this is the issue:
https://github.com/Peter-Schorn/SpotifyAPI/blob/9cc938b41d50eeb5ef8d25431d1d084100f40cc8/Sources/SpotifyWebAPI/Other/MiscellaneousUtilities.swift#L256-L258

This was supposed to be:
```swift
if minOffset >= maxOffset {
    return []
}
```
This will prevent crashes.

**Comment by Peter-Schorn** [comment]
Please try https://github.com/Peter-Schorn/SpotifyAPI/commit/39fd1be211ff355ee29b67abcdacf38b45da57d8.

**Comment by wiencheck** [comment]
After testing it seems that the issue is now resolved, thank you!
