### ISSUE TITLE
Audiobooks API calls not supported or not functional

### ISSUE THREAD

**Issue by gregggreg** [Peter-Schorn/SpotifyAPI#67]
Some audiobook API calls are missing like "Get Audiobook Chapters". 

"Get User's Saved Audiobooks" aka `currentUserSavedAudiobooks` throws an error if you try to use it. It appears it is trying to retrieve SavedAudiobook objects, but the endpoint returns normal Audiobook objects.

It would be nice if we were able to use all of the audiobooks-related APIs in this project. I would possibly be willing to sponsor such a feature if you can provide a cost estimate.

Thanks.

**Comment by Peter-Schorn** [comment]
Hi Greg.

Thanks for bringing these issues with the audiobook endpoints to my attention. I have now started working on fixing them. You can expect a new release within a week or so.

**Comment by gregggreg** [comment]
Thanks so much for looking into this. If it helps I now realize that saved audiobooks seem to show up in the Get User's Saved Shows API already along with podcasts. So for now I can use that and just show them along with podcasts. 

And unfortunately there doesn't seem to be any way in the API (on Spotify's side) to differentiate between podcasts and audiobooks in the user saved shows API response, which is unfortunate since I would like to show audiobooks and podcasts separately when the audiobooks APIs are functional. It is weird that they have separate API calls for podcasts (shows) and audiobooks, but audiobooks show up in both.

**Comment by Peter-Schorn** [comment]
I'm not near my computer right now, but have you checked the `type` property of the `Show` objects?

**Comment by gregggreg** [comment]
> I'm not near my computer right now, but have you checked the `type` property of the `Show` objects?

Yes, the type is always "show" for both podcasts and audiobooks using that endpoint. It is "audiobook" if you use the user saved audiobook endpoints.

And the media_type is always "audio". I've looked at the full JSON response and there is no way to distinguish that I can see using that endpoint. I will try to raise this issue with Spotify on their forums since the issue is on their end.

I guess it would be possible to filter shows to just podcasts by also hitting the audiobook endpoint and filtering out anything it returns, but that is obviously very wasteful.

I appreciate the help. Cheers.

**Comment by Peter-Schorn** [comment]
Just released version 4.0.0. 

* Added `SpotifyAPI.audiobookChapters(_:market:limit:offset:)`.
* `SpotifyAPI.currentUserSavedAudiobooks(limit:offset:)` now returns the correct type: `PagingObject<Audiobook>` instead of `PagingObject<SavedAudiobook>`.

If you encounter any more issues, please feel free to open a new issue!
