### ISSUE TITLE
Web API deprecations as of 2024-11-27

### ISSUE THREAD

**Issue by danwood** [Peter-Schorn/SpotifyAPI#69]
Just discovered this very sad news. I have to rip out much functionality of my in-progress app.

https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

Anyhow, it might be useful to mark the corresponding Swift APIs as deprecated.... or some similar indication that it might not be a good idea to start a new project using those APIs.

**Comment by Peter-Schorn** [comment]
Thanks for sending me this article! I had encountered 403/404 http errors when using these endpoints during my unit tests and had assumed that Spotify had removed support for them completely. It will take me some time to update my library in response to this change. 

I'll probably have to update the doc comments for these methods to indicate that these endpoints are deprecated. 

If I were to use the `@available` annotation to mark the corresponding `SpotifyAPI` methods as deprecated, then even projects using an "[Application] with existing extended mode Web API access" and therefore still have access to these endpoints (per the above article) will recieve a deprecation warning in Xcode which cannot be silenced.
